kind: Deployment
metadata:
  name: nginx-test
spec:
  selector:
    matchLabels:
      app: nginx-test
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: docker.richardjameskendall.com/test-nginx
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
